spring:
  config:
    import: optional:dotenv:./.env

  profiles:
    active:
      - dev

  application:
    name: monew

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
    open-in-view: false


logging:
  level:
    root: info

springdoc:
  swagger-ui:
    path: /api-docs-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: list

  api-docs:
    path: /my-api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: false

info:
  app:
    name: monew
    description: ?? ??? ? ???
    version: 1.0.0
    encoding: UTF-8
    java-version: 17
    spring-version: 3.5.9

naver:
  api:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

aws:
  s3:
    bucket:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
      region: ${AWS_REGION}
      name: ${AWS_S3_BUCKET}
